CREATE TABLE TESTONE(
	ID INT PRIMARY KEY,
	RECENTTITLE VARCHAR(200) NOT NULL,
	RECENTARTIST VARCHAR(200) NOT NULL,
	FOREIK INT NOT NULL
);

CREATE TABLE TESTTWO( 
	NUM INT PRIMARY KEY,
	TITLE VARCHAR(200) NOT NULL,
	ARTIST VARCHAR(200) NOT NULL
	);

INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (1, '소원을말해봐', '소녀시대', 101);
INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (2,'깃허브', '이향준', 102);
INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (3,'둘리', '둘리', 103);
INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (4,'둘리', '둘리', 103);
INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (5,'짱구', '짱구', 105);
INSERT INTO TESTONE(ID, RECENTTITLE, RECENTARTIST, FOREIK) VALUES (6,'이향준', '삼림욕', 105);

INSERT INTO TESTTWO VALUES(101, '다시만난세계', '소녀시대');
INSERT INTO TESTTWO VALUES(102, '우리의꿈', '이향준');
INSERT INTO TESTTWO VALUES(103, '사랑했지만', '황지민');
INSERT INTO TESTTWO VALUES(104, '둘리', '둘리');
INSERT INTO TESTTWO VALUES(105, '둘리', '짱구');

SELECT DISTINCT RECENTTITLE, RECENTARTIST FROM TESTONE WHERE ID BETWEEN 1 AND 5 ;
SELECT DISTINCT TRUNC(DBMS_RANDOM.VALUE(1,5)) FROM TESTONE;
SELECT DBMS_RANDOM.STRING('P', 20) FROM TESTONE;
SELECT * FROM TESTONE WHERE RECENTTITLE, RECENTARTIST NOT IN(SELECT TITLE, ARTIST FROM TESTTWO WHERE TITLE, ARTIST IS NOT NULL);
	
SELECT SYSDATE  FROM TESTONE;
SELECT SYSDATE FROM TESTTWO;

DROP TABLE TESTONE;
SELECT * FROM TESTONE;
SELECT * FROM TESTTWO;